# Site settings
title: Nicolas Carrier's personal page
email: carrier.nicolas0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Posts on programming and free software-related topics, mainly for Linux.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ncarrier.github.io/" # the base hostname & protocol for your site
future: true

# Build settings
markdown: kramdown
